upgrade to v8.1.1
AnacondaRecipes/curl-feedstock pull request #25
Opened 2023-05-24 11:53 UTC by rafaelmartins

2023-05-24 11:54 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

INFO: /tmp/abs_d7fk_urr1n/clone/recipe/meta.yaml:0: output_missing_script: output "libcurl": Output is missing script.
ERROR: /tmp/abs_d7fk_urr1n/clone/recipe/meta.yaml:77: host_section_needs_exact_pinnings: output "libcurl-static": Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_d7fk_urr1n/clone/recipe/meta.yaml:96: host_section_needs_exact_pinnings: output "curl": Packages in host must have exact version pinnings, except python build tools.
WARNING: /tmp/abs_d7fk_urr1n/clone/recipe/meta.yaml:120: license_file_overspecified: Using license_file and license_url is overspecified.
Errors were found

</details>

2023-05-24 15:40 UTC, AndrewVallette approved these changes
LGTM 👍

2023-05-24 16:13 UTC, ViridianMelody approved these changes

2023-05-24 16:25 UTC, ViridianMelody requested changes
The license is very similar to MIT, but still proprietary. We should use `license_family: PROPRIETARY`. It also might be a good idea to drop either the license_file or the license_url. Otherwise, looks good!

2023-05-24 16:56 UTC, rafaelmartins commented
> The license is very similar to MIT, but still proprietary. We should use `license_family: PROPRIETARY`. It also might be a good idea to drop either the license_file or the license_url. Otherwise, looks good!

While I agree that it is not exactly MIT, it is not PROPRIETARY either. I believe that saying that MIT is a license family, given the similarity, is fair enough. also, we have the problem that we can't use "NONE" as license_family.

2023-05-24 17:04 UTC, ViridianMelody approved these changes

2023-05-24 17:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

INFO: /tmp/abs_133a0gp_jn/clone/recipe/meta.yaml:0: output_missing_script: output "libcurl": Output is missing script.
ERROR: /tmp/abs_133a0gp_jn/clone/recipe/meta.yaml:77: host_section_needs_exact_pinnings: output "libcurl-static": Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_133a0gp_jn/clone/recipe/meta.yaml:96: host_section_needs_exact_pinnings: output "curl": Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-05-24 17:12 UTC, rafaelmartins commented
> LGTM! My only suggestion would be to remove the `license_file` as it seems inaccurate and/or out of date.

removed, thanks! also, thanks @ViridianMelody

2023-05-30 07:45 UTC, merged

2023-05-30 07:46 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

INFO: /tmp/abs_22mcwmhb6u/clone/recipe/meta.yaml:0: output_missing_script: output "libcurl": Output is missing script.
ERROR: /tmp/abs_22mcwmhb6u/clone/recipe/meta.yaml:77: host_section_needs_exact_pinnings: output "libcurl-static": Packages in host must have exact version pinnings, except python build tools.
ERROR: /tmp/abs_22mcwmhb6u/clone/recipe/meta.yaml:96: host_section_needs_exact_pinnings: output "curl": Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>